/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WomensHealthRouteImport } from './routes/womens-health'
import { Route as TeamRouteImport } from './routes/team'
import { Route as PhysicalHealthRouteImport } from './routes/physical-health'
import { Route as NewPatientsRouteImport } from './routes/new-patients'
import { Route as IvDripServicesRouteImport } from './routes/iv-drip-services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConciergeMedicineRouteImport } from './routes/concierge-medicine'
import { Route as BehavioralHealthRouteImport } from './routes/behavioral-health'
import { Route as AccessPlanRouteImport } from './routes/access-plan'
import { Route as IndexRouteImport } from './routes/index'

const WomensHealthRoute = WomensHealthRouteImport.update({
  id: '/womens-health',
  path: '/womens-health',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicalHealthRoute = PhysicalHealthRouteImport.update({
  id: '/physical-health',
  path: '/physical-health',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPatientsRoute = NewPatientsRouteImport.update({
  id: '/new-patients',
  path: '/new-patients',
  getParentRoute: () => rootRouteImport,
} as any)
const IvDripServicesRoute = IvDripServicesRouteImport.update({
  id: '/iv-drip-services',
  path: '/iv-drip-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergeMedicineRoute = ConciergeMedicineRouteImport.update({
  id: '/concierge-medicine',
  path: '/concierge-medicine',
  getParentRoute: () => rootRouteImport,
} as any)
const BehavioralHealthRoute = BehavioralHealthRouteImport.update({
  id: '/behavioral-health',
  path: '/behavioral-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessPlanRoute = AccessPlanRouteImport.update({
  id: '/access-plan',
  path: '/access-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-plan': typeof AccessPlanRoute
  '/behavioral-health': typeof BehavioralHealthRoute
  '/concierge-medicine': typeof ConciergeMedicineRoute
  '/contact': typeof ContactRoute
  '/iv-drip-services': typeof IvDripServicesRoute
  '/new-patients': typeof NewPatientsRoute
  '/physical-health': typeof PhysicalHealthRoute
  '/team': typeof TeamRoute
  '/womens-health': typeof WomensHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-plan': typeof AccessPlanRoute
  '/behavioral-health': typeof BehavioralHealthRoute
  '/concierge-medicine': typeof ConciergeMedicineRoute
  '/contact': typeof ContactRoute
  '/iv-drip-services': typeof IvDripServicesRoute
  '/new-patients': typeof NewPatientsRoute
  '/physical-health': typeof PhysicalHealthRoute
  '/team': typeof TeamRoute
  '/womens-health': typeof WomensHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-plan': typeof AccessPlanRoute
  '/behavioral-health': typeof BehavioralHealthRoute
  '/concierge-medicine': typeof ConciergeMedicineRoute
  '/contact': typeof ContactRoute
  '/iv-drip-services': typeof IvDripServicesRoute
  '/new-patients': typeof NewPatientsRoute
  '/physical-health': typeof PhysicalHealthRoute
  '/team': typeof TeamRoute
  '/womens-health': typeof WomensHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-plan'
    | '/behavioral-health'
    | '/concierge-medicine'
    | '/contact'
    | '/iv-drip-services'
    | '/new-patients'
    | '/physical-health'
    | '/team'
    | '/womens-health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-plan'
    | '/behavioral-health'
    | '/concierge-medicine'
    | '/contact'
    | '/iv-drip-services'
    | '/new-patients'
    | '/physical-health'
    | '/team'
    | '/womens-health'
  id:
    | '__root__'
    | '/'
    | '/access-plan'
    | '/behavioral-health'
    | '/concierge-medicine'
    | '/contact'
    | '/iv-drip-services'
    | '/new-patients'
    | '/physical-health'
    | '/team'
    | '/womens-health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessPlanRoute: typeof AccessPlanRoute
  BehavioralHealthRoute: typeof BehavioralHealthRoute
  ConciergeMedicineRoute: typeof ConciergeMedicineRoute
  ContactRoute: typeof ContactRoute
  IvDripServicesRoute: typeof IvDripServicesRoute
  NewPatientsRoute: typeof NewPatientsRoute
  PhysicalHealthRoute: typeof PhysicalHealthRoute
  TeamRoute: typeof TeamRoute
  WomensHealthRoute: typeof WomensHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/womens-health': {
      id: '/womens-health'
      path: '/womens-health'
      fullPath: '/womens-health'
      preLoaderRoute: typeof WomensHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physical-health': {
      id: '/physical-health'
      path: '/physical-health'
      fullPath: '/physical-health'
      preLoaderRoute: typeof PhysicalHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-patients': {
      id: '/new-patients'
      path: '/new-patients'
      fullPath: '/new-patients'
      preLoaderRoute: typeof NewPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iv-drip-services': {
      id: '/iv-drip-services'
      path: '/iv-drip-services'
      fullPath: '/iv-drip-services'
      preLoaderRoute: typeof IvDripServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concierge-medicine': {
      id: '/concierge-medicine'
      path: '/concierge-medicine'
      fullPath: '/concierge-medicine'
      preLoaderRoute: typeof ConciergeMedicineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/behavioral-health': {
      id: '/behavioral-health'
      path: '/behavioral-health'
      fullPath: '/behavioral-health'
      preLoaderRoute: typeof BehavioralHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-plan': {
      id: '/access-plan'
      path: '/access-plan'
      fullPath: '/access-plan'
      preLoaderRoute: typeof AccessPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessPlanRoute: AccessPlanRoute,
  BehavioralHealthRoute: BehavioralHealthRoute,
  ConciergeMedicineRoute: ConciergeMedicineRoute,
  ContactRoute: ContactRoute,
  IvDripServicesRoute: IvDripServicesRoute,
  NewPatientsRoute: NewPatientsRoute,
  PhysicalHealthRoute: PhysicalHealthRoute,
  TeamRoute: TeamRoute,
  WomensHealthRoute: WomensHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
